server:
  port: '8080'

database:
  host: '127.0.0.1'
  port: '3306'
  user: 'root'
  password: '123456'
  name: 'sports_app'

logs_database:
  host: '127.0.0.1'
  port: '3306'
  user: 'root'
  password: '123456'
  name: 'sports_app_logs'

jwt:
  secret: 'your-secret-key'
