server:
  port: '8080'

database:
  host: 'localhost'
  port: '3306'
  user: 'root'
  password: '123456'
  name: 'sports_app'

logs_database:
  host: 'localhost'
  port: '3306'
  user: 'root'
  password: '123456'
  name: 'sports_app_logs'

jwt:
  secret: 'your-secret-key'
