# 文件路径：.github/workflows/deploy-backend.yml
name: Auto Deploy Backend

on:
  push:
    # 只有 backend 目录下的文件有变动时才触发
    paths:
      - 'backend/**'
    branches:
      - master     # 或者你主干所在分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 触发远程部署脚本
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}    # 在仓库 Secrets 里添加你的私钥
        port: 22
        script: |
          set -e
          cd /www/wwwroot/redamancy/backend
          # 拉取最新代码
          git fetch --all
          git reset --hard origin/master
          # 编译 Linux 可执行文件
          GOOS=linux GOARCH=amd64 go build -o redamancy-backend .
          chmod +x redamancy-backend
          # 重启服务（可改为 systemd 重启命令）
          pkill -f redamancy-backend || true
          nohup ./redamancy-backend > backend.log 2>&1 &
