name: CI/CD 后端部署

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout 代码
        uses: actions/checkout@v3

      # 2. Setup Go
      - name: Setup Go 1.23.4
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      # 3. 静态编译并打包
      - name: 静态编译并打包
        run: |
          cd backend
          go mod tidy
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o sports-app-linux
          tar czf ../sports-app-linux.tar.gz sports-app-linux

      # 4. 上传包到 /root/backend
      - name: 上传包
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "sports-app-linux.tar.gz"
          target: "/root/backend/"

      # 5. 部署并用 tmux 启动后台进程
      - name: 部署并启动服务 (tmux)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            # 解包
            mkdir -p /root/backend
            tar xzf /root/backend/sports-app-linux.tar.gz -C /root/backend/
            rm /root/backend/sports-app-linux.tar.gz

            # 覆盖二进制
            mv -f /root/backend/sports-app-linux /www/wwwroot/redamancy/backend/sports-app-linux
            chmod +x /www/wwwroot/redamancy/backend/sports-app-linux

            # 写入 .env
            cat > /www/wwwroot/redamancy/backend/.env << 'EOF'
            OSS_ACCESS_KEY_ID=${{ secrets.OSS_ACCESS_KEY_ID }}
            OSS_ACCESS_KEY_SECRET=${{ secrets.OSS_ACCESS_KEY_SECRET }}
            OSS_ENDPOINT=oss-cn-hangzhou.aliyuncs.com
            OSS_BUCKET=sports-app-images
            # 如有数据库配置，可继续在此添加：
            # DB_HOST=${{ secrets.DB_HOST }}
            # DB_PORT=${{ secrets.DB_PORT }}
            # DB_USER=${{ secrets.DB_USER }}
            # DB_PASS=${{ secrets.DB_PASS }}
            # DB_NAME=${{ secrets.DB_NAME }}
            EOF

            # 确保日志目录
            mkdir -p /www/wwwroot/redamancy/backend/logs

            # 安装 tmux（如果没安装）
            if ! command -v tmux >/dev/null; then
              sudo apt-get update
              sudo apt-get install -y tmux
            fi

            # 杀掉旧的 tmux 会话
            tmux kill-session -t sports-app || true

            # 启动新会话，后台跑服务并落日志
            tmux new-session -d -s sports-app \
              "/www/wwwroot/redamancy/backend/sports-app-linux \
                > /www/wwwroot/redamancy/backend/logs/app.log 2>&1"

            # 立即退出脚本
            exit 0
