name: CI/CD 后端部署

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout 代码
        uses: actions/checkout@v3

      # 2. Setup Go
      - name: Setup Go 1.23.4
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      # 3. 静态编译并打包
      - name: 静态编译并打包
        run: |
          cd backend
          go mod tidy
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o sports-app-linux
          tar czf ../sports-app-linux.tar.gz sports-app-linux

      # 4. 上传二进制包到 /root/backend
      - name: 上传二进制包
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "sports-app-linux.tar.gz"
          target: "/root/backend/"

      # 5. 确保 static 目录存在
      - name: 创建 static 目录
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /www/wwwroot/redamancy/backend/static

      # 6. 上传 favicon.ico
      - name: 上传 favicon.ico
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend/static/favicon.ico"
          target: "/www/wwwroot/redamancy/backend/static/"

      # 7. 部署并启动服务 (tmux)
      - name: 部署并启动服务 (tmux)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            # 解包 & 覆盖二进制
            mkdir -p /root/backend
            tar xzf /root/backend/sports-app-linux.tar.gz -C /root/backend/
            rm   /root/backend/sports-app-linux.tar.gz
            mv -f /root/backend/sports-app-linux /www/wwwroot/redamancy/backend/sports-app-linux
            chmod +x /www/wwwroot/redamancy/backend/sports-app-linux

            # 写入 .env（仅 OSS 配置，按需添加 DB 等）
            cat > /www/wwwroot/redamancy/backend/.env << 'EOF'
            OSS_ACCESS_KEY_ID=${{ secrets.OSS_ACCESS_KEY_ID }}
            OSS_ACCESS_KEY_SECRET=${{ secrets.OSS_ACCESS_KEY_SECRET }}
            OSS_ENDPOINT=oss-cn-hangzhou.aliyuncs.com
            OSS_BUCKET=sports-app-images
            EOF

            # 确保日志目录存在
            mkdir -p /www/wwwroot/redamancy/backend/logs

            # 安装 tmux（支持 CentOS/Alinux）
            if ! command -v tmux >/dev/null; then
              if command -v yum >/dev/null; then
                sudo yum install -y tmux
              elif command -v dnf >/dev/null; then
                sudo dnf install -y tmux
              else
                echo "Error: no supported package manager to install tmux" >&2
                exit 1
              fi
            fi

            # 重启 tmux 会话
            tmux kill-session -t sports-app || true
            tmux new-session -d -s sports-app \
              "/www/wwwroot/redamancy/backend/sports-app-linux \
                > /www/wwwroot/redamancy/backend/logs/app.log 2>&1"

            exit 0
