# .github/workflows/deploy.yml
name: CI/CD 后端部署

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout 代码
        uses: actions/checkout@v3

      # 2. Setup Go
      - name: Setup Go 1.23.4
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      # 3. 编译并打包二进制
      - name: 编译并打包
        run: |
          cd backend
          go mod tidy
          # 静态编译，生成无需动态依赖的可执行文件
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o sports-app-linux
          tar czf ../sports-app-linux.tar.gz sports-app-linux

      # 4. 在服务器上创建部署所需目录
      - name: 创建部署目录
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            mkdir -p /root/backend
            mkdir -p /www/wwwroot/redamancy/backend/static
            mkdir -p /www/wwwroot/redamancy/backend/logs

      # 5. 上传二进制包
      - name: 上传二进制包
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "sports-app-linux.tar.gz"
          target: "/root/backend/"

      # 6. 上传 favicon.ico
      - name: 上传 favicon.ico
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend/static/favicon.ico"
          target: "/www/wwwroot/redamancy/backend/static/"

      # 7. 部署并重启后端进程
      - name: 部署并重启后端
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          timeout: "600s"
          command_timeout: "600s"
          script: |
            set -e

            # 解包 & 覆盖可执行文件
            tar xzf /root/backend/sports-app-linux.tar.gz -C /root/backend/
            mv -f /root/backend/sports-app-linux /www/wwwroot/redamancy/backend/sports-app-linux
            chmod +x /www/wwwroot/redamancy/backend/sports-app-linux

            # 写入 .env
            cat > /www/wwwroot/redamancy/backend/.env << 'EOF'
            OSS_ACCESS_KEY_ID=${{ secrets.OSS_ACCESS_KEY_ID }}
            OSS_ACCESS_KEY_SECRET=${{ secrets.OSS_ACCESS_KEY_SECRET }}
            OSS_ENDPOINT=oss-cn-hangzhou.aliyuncs.com
            OSS_BUCKET=sports-app-images
            EOF

            # 停掉旧进程
            pkill -f sports-app-linux || true

            # 后台启动新进程
            nohup /www/wwwroot/redamancy/backend/sports-app-linux \
              > /www/wwwroot/redamancy/backend/logs/app.log 2>&1 < /dev/null &

            exit 0
