name: CI/CD 后端部署

on:
  push:
    branches:
      - master     # 推送到 master 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 代码
      - name: Checkout 代码
        uses: actions/checkout@v3

      # 2. 缓存 Go modules（支持在任意子目录的 go.sum）
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 3. 设置 Go 1.23.4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      # 4. 下载依赖并编译（在 backend 目录下）
      - name: Download dependencies & Build
        working-directory: backend
        run: |
          go mod download
          go build -o sports-app-linux

      # 5. 上传二进制到服务器
      - name: 上传二进制
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend/sports-app-linux"
          target: "/www/wwwroot/redamancy/backend/"

      # 6. 在服务器上生成 .env（注入 OSS 密钥）
      - name: 上传 .env 到服务器
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cat > /www/wwwroot/redamancy/backend/.env << 'EOF'
            OSS_ACCESS_KEY_ID=${{ secrets.OSS_ACCESS_KEY_ID }}
            OSS_ACCESS_KEY_SECRET=${{ secrets.OSS_ACCESS_KEY_SECRET }}
            OSS_ENDPOINT=oss-cn-hangzhou.aliyuncs.com
            OSS_BUCKET=sports-app-images
            EOF

      # 7. 重启 systemd 服务
      - name: 重启 systemd 服务
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart sports-app.service
