name: CI/CD 后端部署

on:
  push:
    branches:
      - master     # 触发分支改为 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout 代码
        uses: actions/checkout@v3

      # 2. 设置 Go 环境
      - name: Setup Go 1.23.4
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      # 3. 进入 backend 目录，下载依赖并编译
      - name: Build sports-app-linux
        run: |
          cd backend
          go mod tidy
          go mod download
          go build -o sports-app-linux

      # 4. 上传二进制到你的阿里云服务器
      - name: 上传二进制
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend/sports-app-linux"
          target: "/www/wwwroot/redamancy/backend/"

      # 5. 生成 .env（注入 OSS 密钥）
      - name: 上传 .env 到服务器
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cat > /www/wwwroot/redamancy/backend/.env << 'EOF'
            OSS_ACCESS_KEY_ID=${{ secrets.OSS_ACCESS_KEY_ID }}
            OSS_ACCESS_KEY_SECRET=${{ secrets.OSS_ACCESS_KEY_SECRET }}
            OSS_ENDPOINT=oss-cn-hangzhou.aliyuncs.com
            OSS_BUCKET=sports-app-images
            EOF

      # 6. 重启 systemd 服务
      - name: 重启 systemd 服务
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart sports-app.service
