name: CI/CD 后端部署

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout 代码
        uses: actions/checkout@v3

      # 2. Setup Go
      - name: Setup Go 1.23.4
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      # 3. 编译并打包
      - name: 静态编译并打包
        run: |
          cd backend
          go mod tidy
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
            go build -a -installsuffix cgo -o sports-app-linux
          tar czf ../sports-app-linux.tar.gz sports-app-linux

      # 4. 上传二进制包 & favicon 到服务器
      - name: 上传部署文件
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: |
            sports-app-linux.tar.gz
            backend/static/favicon.ico
          target: "/root/backend/"

      # 5. 部署并创建/重启 systemd 服务
      - name: 部署并重启 systemd 服务
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            # 保证目录结构
            mkdir -p /root/backend \
                     /www/wwwroot/redamancy/backend/static \
                     /www/wwwroot/redamancy/backend/logs

            # 解包并覆盖二进制
            tar xzf /root/backend/sports-app-linux.tar.gz -C /root/backend/
            mv -f /root/backend/sports-app-linux /www/wwwroot/redamancy/backend/sports-app-linux
            chmod +x /www/wwwroot/redamancy/backend/sports-app-linux

            # 覆盖 favicon
            mv -f /root/backend/favicon.ico /www/wwwroot/redamancy/backend/static/favicon.ico

            # 生成 .env
            cat > /www/wwwroot/redamancy/backend/.env << 'EOF'
            OSS_ACCESS_KEY_ID=${{ secrets.OSS_ACCESS_KEY_ID }}
            OSS_ACCESS_KEY_SECRET=${{ secrets.OSS_ACCESS_KEY_SECRET }}
            OSS_ENDPOINT=oss-cn-hangzhou.aliyuncs.com
            OSS_BUCKET=sports-app-images
            EOF

            # 写入 systemd 单元（有则覆盖，无则新建）
            cat > /etc/systemd/system/sports-app.service << 'EOF'
            [Unit]
            Description=Sports App Backend Service
            After=network.target

            [Service]
            User=root
            WorkingDirectory=/www/wwwroot/redamancy/backend
            EnvironmentFile=/www/wwwroot/redamancy/backend/.env
            ExecStart=/www/wwwroot/redamancy/backend/sports-app-linux
            Restart=on-failure
            RestartSec=5

            [Install]
            WantedBy=multi-user.target
            EOF

            # 重载、启用并重启服务
            systemctl daemon-reload
            systemctl enable sports-app.service
            systemctl restart sports-app.service

            exit 0
