name: CI/CD 后端部署

on:
  push:
    branches:
      - master     # 改为 master 分支触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 代码
      - name: Checkout 代码
        uses: actions/checkout@v3

      # 2. 缓存 Go modules（假设 go.mod/go.sum 在 backend 目录下）
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 3. 设置 Go 环境
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'  # 改为你项目使用的 Go 版本

      # 4. 在 backend 目录下编译二进制
      - name: Build sports-app-linux
        working-directory: backend
        run: go build -o sports-app-linux

      # 5. 上传二进制到服务器
      - name: 上传二进制
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend/sports-app-linux"
          target: "/www/wwwroot/redamancy/backend/"

      # 6. 在服务器上写入 .env（注入 OSS 密钥）
      - name: 上传 .env 到服务器
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cat > /www/wwwroot/redamancy/backend/.env <<EOF
            OSS_ACCESS_KEY_ID=${{ secrets.OSS_ACCESS_KEY_ID }}
            OSS_ACCESS_KEY_SECRET=${{ secrets.OSS_ACCESS_KEY_SECRET }}
            OSS_ENDPOINT=oss-cn-hangzhou.aliyuncs.com
            OSS_BUCKET=sports-app-images
            EOF

      # 7. 重启 systemd 服务
      - name: 重启 systemd 服务
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart sports-app.service
