name: CI/CD 后端部署

on:
  push:
    branches:
      - master     # 触发分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout 代码
        uses: actions/checkout@v3

      # 2. 设置 Go 环境
      - name: Setup Go 1.23.4
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      # 3. 编译后端二进制
      - name: Build sports-app-linux
        run: |
          cd backend
          go mod tidy
          go mod download
          go build -o sports-app-linux

      # 4. 删除 /root 下旧二进制
      - name: 删除 /root 旧二进制
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -f /root/sports-app-linux

      # 5. 上传新二进制到 /root
      - name: 上传二进制到 /root
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend/sports-app-linux"
          target: "/root/"

      # 6. 在服务器上覆盖部署、生成 .env 并重启服务
      - name: 部署并重启服务
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 强制删除旧二进制并覆盖
            rm -f /www/wwwroot/redamancy/backend/sports-app-linux
            mv -f /root/sports-app-linux /www/wwwroot/redamancy/backend/sports-app-linux
            chmod +x /www/wwwroot/redamancy/backend/sports-app-linux

            # 生成最新 .env（注入 OSS 密钥）
            cat > /www/wwwroot/redamancy/backend/.env << 'EOF'
            OSS_ACCESS_KEY_ID=${{ secrets.OSS_ACCESS_KEY_ID }}
            OSS_ACCESS_KEY_SECRET=${{ secrets.OSS_ACCESS_KEY_SECRET }}
            OSS_ENDPOINT=oss-cn-hangzhou.aliyuncs.com
            OSS_BUCKET=sports-app-images
            EOF

            # 重载并重启 systemd 服务
            sudo systemctl daemon-reload
            sudo systemctl restart sports-app.service
